version: '3.8'

services:
  api:
    build: .
    hostname: api
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://rinha:rinha@db:5432/rinha
      - REDIS_URL=redis://redis:6379
      - DATABASE_POOL_MIN_SIZE=3
      - DATABASE_POOL_MAX_SIZE=15
      - REDIS_POOL_SIZE=8
      - CACHE_TTL=300
      - PYTHONOPTIMIZE=1
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - GUNICORN_WORKERS=1
      - GUNICORN_WORKER_CONNECTIONS=50
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1GB'
        reservations:
          memory: '512MB'
    networks:
      - rinha-network

  nginx:
    image: nginx:alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '256MB'
    networks:
      - rinha-network

  db:
    image: postgres:15-alpine
    hostname: db
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '1.5GB'
    networks:
      - rinha-network

  redis:
    image: redis:7-alpine
    hostname: redis
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru --save "" --appendonly no
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '256MB'
        reservations:
          memory: '64MB'
    networks:
      - rinha-network

networks:
  rinha-network:
    driver: bridge
